<a href="https://colab.research.google.com/github/TYZAUM/maiWorkshops19/blob/master/MAI(kur_A).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
print("MAI Practice")
c=input("Yazarın Adı:")
a= "MAI Practice"
print(a)
print(type(a))
print("Bu yazı {} tarafından yazılmıştır.".format(c))

b= 64
print(b)
print(type(b))

c= 64.0
print(c)
print(type(c))

d=(1,2,3,6,"helva",8,5)
print(d)
print(type(d))
print(d[1])

e= {"z":1,"x":2,"v":3}
print(e)
print(type(e))
print(type("z"))

f = [1,2,3,7,9,11,"armut"]
print(f)
print(type(f))
f.append(15)
print(f)
f.remove(9)
print(f)
f.insert(3,"apple")
print(f)

MAI Practice
Yazarın Adı:yavuz
MAI Practice
<class 'str'>
Bu yazı yavuz tarafından yazılmıştır.
64
<class 'int'>
64.0
<class 'float'>
(1, 2, 3, 6, 'helva', 8, 5)
<class 'tuple'>
2
{'z': 1, 'x': 2, 'v': 3}
<class 'dict'>
<class 'str'>
[1, 2, 3, 7, 9, 11, 'armut']
<class 'list'>
[1, 2, 3, 7, 9, 11, 'armut', 15]
[1, 2, 3, 7, 11, 'armut', 15]
[1, 2, 3, 'apple', 7, 11, 'armut', 15]

In [0]:
bir_say = 45
iki_say = 674
üc_say = 4

a= bir_say + iki_say
b= bir_say - iki_say
c= bir_say * iki_say
d= bir_say ** üc_say
e= bir_say / iki_say
f= iki_say // bir_say
g= iki_say % bir_say
h=divmod(iki_say,bir_say)
ı=bir_say*h[0]+h[1]


print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(ı)

719
-629
30330
4100625
0.06676557863501484
14
44
(14, 44)
674

In [0]:
"THE REAL OPERATORS!!"
y=2
x=3
print(x==3)

x += 1
print(x)

x -= 1
print(x)

x *= 2
print(x)

x /= 3
print(x)

print(x != 2)
print(x != 2.0)
print(x is y)
print(id(x))
print(id(y))

"CHECKPOINT"
print("\n-------MAI--------------\n")

if (x == 2):
      print("True Predict!")

else: 
      print("False :(" )




"""
from itertools import islice

t=enumerate(zxc)
print(list(islice(t,3,8)))
print(list(islice(t,0,5)))
print(list(next(islice(t,3,5))))
"""

zxc=["a","s","d","f","g","h","j","k","l","ş","p","o","ı","u","y",
     "t","r"]

print(enumerate(zxc))
print(enumerate(zxc[7]))

cv=(enumerate(zxc))
print(type(cv))
print(list((enumerate(zxc[3]))))
print(list(enumerate(zxc)))

print(next(enumerate(zxc)))

for i in range (0,len(zxc)-5):
        print(i)
        
for i in range(2):
    next(cv)
print(next(cv))

        
for i in range (0,len(zxc)-5):
        print("\n",(next(enumerate(zxc[i]))))

for i in range (0,len(zxc)-5):
        print("\n",(list(enumerate(zxc[i]))))



import random
fg= 0
liste=[]
while fg != 10 :
    fg+=1
    liste.append(random.randint(0,2))

print(liste)

True
4
3
6
2.0
False
False
False
139703058210656
10968832

-------MAI--------------

True Predict!
<enumerate object at 0x7f0f2711eea0>
<enumerate object at 0x7f0f2711eea0>
<class 'enumerate'>
[(0, 'f')]
[(0, 'a'), (1, 's'), (2, 'd'), (3, 'f'), (4, 'g'), (5, 'h'), (6, 'j'), (7, 'k'), (8, 'l'), (9, 'ş'), (10, 'p'), (11, 'o'), (12, 'ı'), (13, 'u'), (14, 'y'), (15, 't'), (16, 'r')]
(0, 'a')
0
1
2
3
4
5
6
7
8
9
10
11
(2, 'd')

 (0, 'a')

 (0, 's')

 (0, 'd')

 (0, 'f')

 (0, 'g')

 (0, 'h')

 (0, 'j')

 (0, 'k')

 (0, 'l')

 (0, 'ş')

 (0, 'p')

 (0, 'o')

 [(0, 'a')]

 [(0, 's')]

 [(0, 'd')]

 [(0, 'f')]

 [(0, 'g')]

 [(0, 'h')]

 [(0, 'j')]

 [(0, 'k')]

 [(0, 'l')]

 [(0, 'ş')]

 [(0, 'p')]

 [(0, 'o')]
[2, 1, 1, 0, 2, 0, 1, 0, 1, 1]

In [0]:
print("\n-------MAI-------------\n")
def function (x):
  return 2*x

print(function(3))

print("\n-------MAI-------------\n")

def function_2 (x,y):
  return x+y

print (function_2(2,3))
print("\n-------MAI-------------\n")

a=3

def function_3(x):
  a=x**2
  print(a)
  
function_3(5)
print (a)
#Fonksiyon içindeki atamalar dışarı yansımaz.
print("\n-------MAI-------------\n")

def function_4(x):
  x+=1
  print(x)
  if x== 10 :
    while True:
      x-=1
      print(x)
      if x==1:
        return "x="+ str(x) + "    \nFunction has stopped!"
  elif x==1:
    return "x="+ str(x) + "    \nFunction has stopped!"
  return function_4(x)

print(function_4(2))
print("\n-------MAI-------------\n")

def function_5(n):  
   if n == 1:  
       return n  
    else:  
       return n*function_5(n-1) 

print(function_5(5))
print("\n-------MAI-------------\n")

-------MAI-------------

6

-------MAI-------------

5

-------MAI-------------

25
3

-------MAI-------------

3
4
5
6
7
8
9
10
9
8
7
6
5
4
3
2
1
x=1
Function has stopped!

-------MAI-------------

120

-------MAI-------------

In [0]:
class MAI:
  avg=0
  ID=0
  def __init__ (self,name, surname, age, department, tel_num,salary,*arg):
    MAI.avg+=salary
    MAI.ID+=1
    self.name=name
    self.surname=surname
    self.age=age
    self.department=department
    self.tel_num=tel_num
    self.salary=salary
    
  def description(self):
        return "{} is {} years old".format(self.name, self.age)
  def salary_ (self):
        return "{} is earning {} $ in a month".format(self.name, self.salary)
  t=(MAI.avg / MAI.ID)
  def salary_test(self):
    t=(MAI.avg / MAI.ID)
    if self.salary < t:
      return "{} 's situation is :Low Salary".format(self.name)
    elif self.salary >= t:
      return "{} 's situation is :High Salary".format(self.name)
      
  def average_salary():
       return "Average salary of MAI members is: {}".format(t)
  

jack= MAI("Jack","Sparrow",23,"Sailing","0542674523",2500)
john= MAI("John","Volt",45,"Sailing","05353745693",3000)
johnny=MAI("Johnny","Bravo",34,"Body_Building","05327854691",5000)


print(jack.__dict__)
print(john.__dict__)
print(jack.salary_())
print(MAI.avg)
print(jack.salary_test())
print(johnny.salary_test())

{'name': 'Jack', 'surname': 'Sparrow', 'age': 23, 'department': 'Sailing', 'tel_num': '0542674523', 'salary': 2500}
{'name': 'John', 'surname': 'Volt', 'age': 45, 'department': 'Sailing', 'tel_num': '05353745693', 'salary': 3000}
Jack is earning 2500 $ in a month
10500
Jack 's situation is :Low Salary
Johnny 's situation is :High Salary

In [0]:
#READ FILES WITH PYTHON
"""
"r" - Read - Default value. Opens a file for reading, error if the file does not exist

"a" - Append - Opens a file for appending, creates the file if it does not exist

"w" - Write - Opens a file for writing, creates the file if it does not exist

"x" - Create - Creates the specified file, returns an error if the file exists
"""
"""
t" - Text - Default value. Text mode

"b" - Binary - Binary mode (e.g. images)
"""

#f = open("/content/sample_data/california_housing_train.csv", "r",encoding="utf-8")
#for i in range (0,10):
import pandas as pd 
#df=pd.read_csv("/content/sample_data/california_housing_train.csv")
#df.head()

f=open("/content/eminem.txt","r+")
veri=f.readlines()
veri.insert(0,"EMINEM LYRICS")

s_word=input("Lütfen boşluk bırakarak aradığınız kelimeleri giriniz:")
s_word2=s_word.split(" ")
print(type(s_word2))
print(len(s_word2))
for i in range (0,len(s_word2)):
  print("\n-------MAI----------------------\n\n\tWord: {}\n".format(s_word2[i]))
  for v in range (0,len(veri)):
    if ("{}".format(s_word2[i])) in veri[v]:
      print(veri[v])
  
#veri

Lütfen boşluk bırakarak aradığınız kelimeleri giriniz:fuck look
<class 'list'>
2

-------MAI----------------------

	Word: fuck

That I'll still be able to break a motherfuckin' table

To meet Run DMC and induct them into the motherfuckin' Rock n'

Off of planking, tell me what in the fuck are you thinking?

And I don't know what the fuck that you rhyme for

You're pointless as Rapunzel with fucking cornrows

You write normal, fuck being normal

How to give a motherfuckin' audience a feeling like it's levitating

But it's still tongue in cheek, fuck you

I'm drunk so Satan take the fucking wheel, I'm asleep in the front seat

But fuck it, life's handing you lemons, make lemonade then

But if I can't batter the women how the fuck am I supposed to bake them a cake then?


-------MAI----------------------

	Word: look

Little gay looking boy

So gay I can barely say it with a straight face looking boy

Like you watching a church gathering take place looking boy

Oy vey, that boy's gay, that's all they say looking boy

And a "way to go" from your label everyday looking boy

Hey, looking boy, what you say looking boy?

I got a "hell yeah" from Dre looking boy

Never ask nobody for shit, get outta my face looking boy

To keep up with the same pace looking boy

Rappers are hungry looking at me like it's lunchtime

'Cause Fab said he looked like a fag at Maywhether's pad

But look at the accolades the skills brung me

In [0]:
import pandas as pd
import numpy as np
a=[]
word_dim=10
hidden_dim=50
a=np.random.uniform(-np.sqrt(1. / word_dim), np.sqrt(1. / word_dim), (hidden_dim, word_dim))
print(a.shape)

df_a=pd.DataFrame(a,columns=["hd_1","hd_2","hd_3","hd_4","hd_5","hd_6","hd_7","hd_8","hd_9","hd_10"])
print(df_a)

#z=np.random.uniform(0,100,(1,20))
#x=np.random.uniform(0,100,(1,20))
#c=np.random.uniform(0,100,(1,20))
q=[]
w=[]
e=[]
d=[q,w,e]
for v in range(0,3):
  for i in range (0,20):
    p=np.random.uniform(0,100,(1,1))
    d[v].append(float(p))
  

medicines={"Dolarex \(mg)":q,"Coraspin Grams: \(mg)":w,"Parol: \(mg)":e}
df= pd.DataFrame(medicines,columns=["Dolarex \(mg)","Coraspin Grams: \(mg)","Parol: \(mg)"])
print(df.shape)
print(df.loc[1][1])
print(df.loc[:,"Coraspin Grams: \(mg)"])
df

(50, 10)
        hd_1      hd_2      hd_3  ...      hd_8      hd_9     hd_10
0  -0.164408  0.107281 -0.034779  ... -0.314167  0.076490 -0.129042
1   0.268098 -0.307399  0.193211  ... -0.190917  0.076910  0.236245
2   0.025180 -0.119127  0.310056  ...  0.068570 -0.193930  0.095833
3   0.253714 -0.280331  0.292253  ... -0.044983  0.310135 -0.179084
4  -0.129171  0.140240  0.091480  ... -0.305819  0.274760  0.254886
5   0.082139 -0.071253  0.110675  ...  0.278800  0.059003  0.131743
6  -0.042496  0.127335  0.033326  ... -0.010742 -0.206523  0.265407
7  -0.234808 -0.256016 -0.199893  ...  0.118209 -0.310404  0.246480
8  -0.313934 -0.146058  0.000839  ...  0.269028  0.117788  0.149643
9  -0.307420  0.010047  0.030093  ...  0.112182 -0.051456 -0.168549
10  0.007359  0.007847  0.271643  ... -0.099182  0.143257 -0.227386
11 -0.267861 -0.037027 -0.082745  ... -0.246097  0.121438 -0.074991
12  0.032362 -0.189856 -0.071842  ...  0.213398 -0.156769  0.096882
13 -0.307131  0.191495  0.033383  ...  0.072874 -0.038905  0.040650
14  0.217488  0.033491  0.244697  ...  0.082763 -0.261144  0.044653
15 -0.083170 -0.032893 -0.175446  ...  0.117968  0.094905 -0.305436
16 -0.211352 -0.314405  0.230710  ... -0.046223 -0.284659  0.133426
17 -0.128696  0.215708 -0.035974  ...  0.258496 -0.312355 -0.040756
18 -0.079715  0.279061  0.121039  ...  0.256009 -0.106583  0.100104
19 -0.264365 -0.198285 -0.050035  ... -0.272582 -0.182165 -0.115662
20 -0.181874  0.039634  0.219728  ...  0.188063 -0.261581 -0.026047
21 -0.167990 -0.267854  0.147030  ... -0.010981  0.108894  0.053732
22  0.147005  0.256527 -0.027000  ...  0.197348 -0.049622 -0.157724
23  0.108268 -0.142511 -0.116046  ...  0.100216 -0.016816  0.238699
24 -0.315654 -0.215887 -0.159905  ...  0.105547  0.105766 -0.208098
25 -0.019962 -0.174043 -0.186018  ... -0.291780  0.013216 -0.129980
26 -0.030997  0.026907  0.131189  ... -0.254509 -0.097180 -0.287248
27 -0.226917 -0.314757 -0.117390  ... -0.115018 -0.059525 -0.037252
28  0.064713  0.251820  0.201101  ...  0.119752 -0.315846 -0.205494
29 -0.102910 -0.302290  0.293201  ... -0.116479  0.024804 -0.276158
30  0.060179 -0.132170  0.197164  ... -0.044730 -0.012772 -0.195715
31  0.305528 -0.066445  0.173641  ... -0.139881  0.007379  0.067919
32  0.231239  0.002280 -0.172372  ... -0.166363  0.291763  0.092339
33 -0.296352 -0.178136 -0.250402  ...  0.101648 -0.197065  0.215270
34  0.013053 -0.213874  0.071288  ... -0.215060 -0.242872  0.055256
35 -0.006283 -0.157680 -0.092316  ... -0.167736 -0.118557 -0.197694
36  0.259162  0.159255  0.274737  ...  0.126176  0.148629 -0.181280
37  0.270783  0.014137  0.207498  ... -0.269876  0.262539 -0.092071
38  0.280849  0.061196 -0.134017  ...  0.069190 -0.262459  0.305594
39  0.313231 -0.287057 -0.280118  ...  0.096215  0.271466  0.255099
40 -0.013414  0.292730  0.048576  ...  0.159451 -0.213625  0.102429
41  0.145682 -0.004084  0.044060  ... -0.203094  0.243415 -0.158073
42 -0.249255 -0.173319  0.160886  ...  0.129357  0.312735 -0.182917
43 -0.152412  0.091655  0.278725  ...  0.250807  0.283307 -0.131232
44  0.207485 -0.244024  0.156871  ... -0.280302 -0.253453  0.036521
45  0.236360 -0.063479  0.158724  ... -0.195228 -0.280292  0.125468
46 -0.161370  0.181149  0.135515  ...  0.156578 -0.200154 -0.111897
47 -0.285002  0.054102 -0.078501  ...  0.011306 -0.121691 -0.145770
48 -0.285706 -0.093205 -0.120651  ... -0.094006  0.309877  0.140036
49 -0.163436 -0.153794  0.049057  ... -0.316084  0.175059  0.236361

[50 rows x 10 columns]
(20, 3)
86.41695535634992
0     48.825584
1     86.416955
2     24.618723
3     79.499217
4     12.293436
5     84.091586
6     79.348925
7     67.045156
8     49.951023
9     15.043984
10    76.904511
11    53.743387
12    71.478825
13    60.842959
14    62.273114
15    11.500069
16    15.109317
17    33.000202
18    10.839465
19    23.230276
Name: Coraspin Grams: \(mg), dtype: float64

    Dolarex \(mg)  Coraspin Grams: \(mg)  Parol: \(mg)
0       92.413965              48.825584     79.988042
1       48.630927              86.416955     89.089826
2       18.203936              24.618723     48.547846
3        0.672899              79.499217     82.076183
4       58.494416              12.293436     83.387333
5       16.939925              84.091586     95.117380
6       10.279409              79.348925     77.187079
7        4.227687              67.045156     39.731839
8       76.309701              49.951023      0.149293
9       58.877257              15.043984     83.180221
10      35.791373              76.904511     62.690609
11       9.054229              53.743387     72.935569
12      90.946412              71.478825     71.047148
13      20.852062              60.842959     12.279683
14      95.914559              62.273114     84.517962
15      64.067258              11.500069     36.928816
16      46.029178              15.109317     32.836096
17      40.876416              33.000202     88.490811
18      58.806982              10.839465     14.982648
19      70.624050              23.230276     36.294427

In [0]:
arm_bones=["humerus","scapula","clavicula","ulna","radius","scaphoid","lunatum","triquetrum","psiformis","trapezium"
                ,"trapoziedum", "capitatum", "hamatum","metacarpals","phalanges(h)"]
leg_bones=["femur","tibia","fibula","calcaneus","talus","medial cuneiform","lateral cuneiform","intermediate cuneiform",
                  "cuboid","metatarsals","phalanges","phalanges(f)"]
neurocranium=["os_occipitalis", "os_parietalis","os_frontalis","os_sphenoidalis","os_ethmoidalis","os_nasalis","os_lacrimalis","os_lacrimalis","os_zygomaticus",
             "os_palatina","inferior nasal concha","vomer","mandibula","os_maxillae"]
vertebra=[]
pelvis_bones=["sacrum","coccyx","ilium","ischium","pubis"]
sesamoid_bones=["patella","pisiform","fabella"]
os_thorax=["hyoid","sternum","ribs"]
a=[arm_bones,leg_bones,neurocranium,vertebra,os_thorax,pelvis_bones,sesamoid_bones]
bones_list=[]

for i in range (0,len(a)):
  for v in range (0,len(a[i])):
    bones_list.append(str(((a[i])[v])))
  for g in range (0,(10-((len(a[i]))%10))):
    bones_list.append("NaN")
    

x=0
t=""

for d in range (0,len(bones_list)):
  x += 1
  if (x%10) == 0:
    t+=("\n\n")
  else :
    pass
  t+=((bones_list[d]))
  r=(22-len(bones_list[d]))
  for m in range (0,r):
    t+=(" ")
  
  
print(t)

humerus               scapula               clavicula             ulna                  radius                scaphoid              lunatum               triquetrum            psiformis

trapezium             trapoziedum           capitatum             hamatum               metacarpals           phalanges(h)          NaN                   NaN                   NaN                   NaN

NaN                   femur                 tibia                 fibula                calcaneus             talus                 medial cuneiform      lateral cuneiform     intermediate cuneiformcuboid

metatarsals           phalanges             phalanges(f)          NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN

NaN                   os_occipitalis        os_parietalis         os_frontalis          os_sphenoidalis       os_ethmoidalis        os_nasalis            os_lacrimalis         os_lacrimalis         os_zygomaticus

os_palatina           inferior nasal concha vomer                 mandibula             os_maxillae           NaN                   NaN                   NaN                   NaN                   NaN

NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN

NaN                   hyoid                 sternum               ribs                  NaN                   NaN                   NaN                   NaN                   NaN                   NaN

NaN                   sacrum                coccyx                ilium                 ischium               pubis                 NaN                   NaN                   NaN                   NaN

NaN                   patella               pisiform              fabella               NaN                   NaN                   NaN                   NaN                   NaN                   NaN

NaN

In [0]:
67%10

7